### ISSUE TITLE
workin apps, append list of apps working for you by this repo 

### ISSUE THREAD

**Issue by Uddhav07** [k0mraid3/Samsung-Galaxy-Book-Windows-Apps-Enabler-Use-Samsung-Windows-Apps-on-Any-Device#6]

**Comment by k0mraid3** [comment]
To clarify, are you asking if I can post a list of known working Samsung PC apps? If that's the question, sure, but give me about a week or so to get to it.

**Comment by Uddhav07** [comment]
yeah, can you confirm if copy paste sync works with thsi since i have 3 devices so link to windows wont work

**Comment by k0mraid3** [comment]
Here is what I've gotten working on my devices. The copy-paste feats seem to work, but I can't be sure if that is because of LTW or multi-control as I have both working fine on my systems. However here is a list of store apps that this got working for me. I also managed to get Samsung Studio working but I had to go in and patch a DLL. It is up on my GitHub profile as a separate project. 
![image](https://github.com/user-attachments/assets/13304b27-7a78-471a-b5d8-a1c49c30a9b9)
